### ISSUE TITLE
Gesamtes Lastenheft + Produktinformation im Pflichtenheft

### ISSUE THREAD

**Issue by aerotunnelbit** [hench96/BratwurstUndSauerkraut#1]

**Comment by hench96** [comment]
- [x]  Lastenheft - Use Cases

- [x] Lastenheft - Produktleistungen

- [ ]  Produktinformationen

**Comment by hench96** [comment]
Lastenheft - Prouktübersicht
nach:
http://swt.informatik.uni-rostock.de/swt_lastenheft.html
